name: Update chrome-driver Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          cache: pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Check Browser and Library Version
        run: |
          browser_version=$(google-chrome --version | sed -e 's/Google Chrome //g' | sed -e 's/ //g')
          browser_major_version=$(echo $browser_version | awk -F . '{print $1}')
          library_version=$(cat Pipfile | grep "chromedriver-binary" | sed -e 's/chromedriver-binary = "==//g' | sed -e 's/.0"//g')
          library_major_version=$(echo $library_version | awk -F . '{print $1}')

          echo "browser_version=${browser_version}" >> $GITHUB_ENV
          echo "browser_major_version=${browser_major_version}" >> $GITHUB_ENV
          echo "library_version=${library_version}" >> $GITHUB_ENV
          echo "library_major_version=${library_major_version}" >> $GITHUB_ENV

          echo "browser_version: ${browser_version}"
          echo "browser_major_version: ${browser_major_version}"
          echo "library_version: ${library_version}"
          echo "library_major_version: ${library_major_version}"
      - name: Replace
        if: env.browser_major_version != env.library_major_version
        run: |
          sed -i "s/${library_major_version}.\*/${browser_major_version}.\*/g" Pipfile
          pipenv update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: env.browser_version != env.library_version
        with:
          delete-branch: true
          title: Update chromium-driver to ${{ env.browser_major_version }}
          commit-message: Update chromium-driver to ${{ env.browser_major_version }}
