name: Update chrome-driver Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0/6 * * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Check Browser and Library Version
        run: |
          browser_version=$(google-chrome --version | sed -e 's/Google Chrome //g' | sed -e 's/ //g')
          library_version=$(cat Pipfile | grep "chromedriver-binary" | sed -e 's/chromedriver-binary = "==//g' | sed -e 's/.0"//g')
          echo "browser_version=${browser_version}" >> $GITHUB_ENV
          echo "library_version=${library_version}" >> $GITHUB_ENV
      - name: Replace
        if: env.browser_version != env.library_version
        run: |
          sed -i "s/${library_version}/${browser_version}/g" Pipfile
          pipenv update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: env.browser_version != env.library_version
        with:
          delete-branch: true
          title: Update chromium-driver to ${{ env.browser_version }}
          commit-message: Update chromium-driver to ${{ env.browser_version }}
